update=18/01/18 11:34:21
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=C:/Program Files/KiCad/share/kicad/library
[eeschema/libraries]
LibName1=SliderBar
LibName2=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName3=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName4=C:/Program Files/KiCad/share/kicad/library/Altera
LibName5=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName6=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName7=C:/Program Files/KiCad/share/kicad/library/atmel
LibName8=C:/Program Files/KiCad/share/kicad/library/audio
LibName9=C:/Program Files/KiCad/share/kicad/library/Battery_Management
LibName10=C:/Program Files/KiCad/share/kicad/library/bbd
LibName11=C:/Program Files/KiCad/share/kicad/library/Bosch
LibName12=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName13=C:/Program Files/KiCad/share/kicad/library/Connector
LibName14=C:/Program Files/KiCad/share/kicad/library/contrib
LibName15=C:/Program Files/KiCad/share/kicad/library/cypress
LibName16=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName17=C:/Program Files/KiCad/share/kicad/library/Decawave
LibName18=C:/Program Files/KiCad/share/kicad/library/device
LibName19=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName20=C:/Program Files/KiCad/share/kicad/library/Diode
LibName21=C:/Program Files/KiCad/share/kicad/library/Display
LibName22=C:/Program Files/KiCad/share/kicad/library/driver_gate
LibName23=C:/Program Files/KiCad/share/kicad/library/dsp
LibName24=C:/Program Files/KiCad/share/kicad/library/DSP_Microchip_DSPIC33
LibName25=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName26=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName27=C:/Program Files/KiCad/share/kicad/library/Espressif
LibName28=C:/Program Files/KiCad/share/kicad/library/FPGA_Actel
LibName29=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName30=C:/Program Files/KiCad/share/kicad/library/gennum
LibName31=C:/Program Files/KiCad/share/kicad/library/Graphic
LibName32=C:/Program Files/KiCad/share/kicad/library/hc11
LibName33=C:/Program Files/KiCad/share/kicad/library/infineon
LibName34=C:/Program Files/KiCad/share/kicad/library/intel
LibName35=C:/Program Files/KiCad/share/kicad/library/interface
LibName36=C:/Program Files/KiCad/share/kicad/library/intersil
LibName37=C:/Program Files/KiCad/share/kicad/library/ir
LibName38=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName39=C:/Program Files/KiCad/share/kicad/library/LED
LibName40=C:/Program Files/KiCad/share/kicad/library/LEM
LibName41=C:/Program Files/KiCad/share/kicad/library/linear
LibName42=C:/Program Files/KiCad/share/kicad/library/Logic_74xgxx
LibName43=C:/Program Files/KiCad/share/kicad/library/Logic_74xx
LibName44=C:/Program Files/KiCad/share/kicad/library/Logic_CMOS_4000
LibName45=C:/Program Files/KiCad/share/kicad/library/Logic_CMOS_IEEE
LibName46=C:/Program Files/KiCad/share/kicad/library/logic_programmable
LibName47=C:/Program Files/KiCad/share/kicad/library/Logic_TTL_IEEE
LibName48=C:/Program Files/KiCad/share/kicad/library/maxim
LibName49=C:/Program Files/KiCad/share/kicad/library/MCU_Microchip_PIC10
LibName50=C:/Program Files/KiCad/share/kicad/library/MCU_Microchip_PIC12
LibName51=C:/Program Files/KiCad/share/kicad/library/MCU_Microchip_PIC16
LibName52=C:/Program Files/KiCad/share/kicad/library/MCU_Microchip_PIC18
LibName53=C:/Program Files/KiCad/share/kicad/library/MCU_Microchip_PIC24
LibName54=C:/Program Files/KiCad/share/kicad/library/MCU_Microchip_PIC32
LibName55=C:/Program Files/KiCad/share/kicad/library/MCU_NXP_Kinetis
LibName56=C:/Program Files/KiCad/share/kicad/library/MCU_NXP_LPC
LibName57=C:/Program Files/KiCad/share/kicad/library/MCU_NXP_S08
LibName58=C:/Program Files/KiCad/share/kicad/library/MCU_Parallax
LibName59=C:/Program Files/KiCad/share/kicad/library/MCU_ST_STM8
LibName60=C:/Program Files/KiCad/share/kicad/library/MCU_ST_STM32
LibName61=C:/Program Files/KiCad/share/kicad/library/MCU_Texas_MSP430
LibName62=C:/Program Files/KiCad/share/kicad/library/Mechanical
LibName63=C:/Program Files/KiCad/share/kicad/library/memory
LibName64=C:/Program Files/KiCad/share/kicad/library/microchip
LibName65=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName66=C:/Program Files/KiCad/share/kicad/library/modules
LibName67=C:/Program Files/KiCad/share/kicad/library/Motor
LibName68=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName69=C:/Program Files/KiCad/share/kicad/library/motorola
LibName70=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName71=C:/Program Files/KiCad/share/kicad/library/nxp
LibName72=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName73=C:/Program Files/KiCad/share/kicad/library/opto
LibName74=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName75=C:/Program Files/KiCad/share/kicad/library/philips
LibName76=C:/Program Files/KiCad/share/kicad/library/power
LibName77=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName78=C:/Program Files/KiCad/share/kicad/library/powerint
LibName79=C:/Program Files/KiCad/share/kicad/library/pspice
LibName80=C:/Program Files/KiCad/share/kicad/library/references
LibName81=C:/Program Files/KiCad/share/kicad/library/regul
LibName82=C:/Program Files/KiCad/share/kicad/library/Relay
LibName83=C:/Program Files/KiCad/share/kicad/library/RF_Bluetooth
LibName84=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName85=C:/Program Files/KiCad/share/kicad/library/RFSolutions
LibName86=C:/Program Files/KiCad/share/kicad/library/Sensor_Current
LibName87=C:/Program Files/KiCad/share/kicad/library/Sensor_Humidity
LibName88=C:/Program Files/KiCad/share/kicad/library/sensors
LibName89=C:/Program Files/KiCad/share/kicad/library/silabs
LibName90=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName91=C:/Program Files/KiCad/share/kicad/library/supertex
LibName92=C:/Program Files/KiCad/share/kicad/library/Switch
LibName93=C:/Program Files/KiCad/share/kicad/library/texas
LibName94=C:/Program Files/KiCad/share/kicad/library/Transformer
LibName95=C:/Program Files/KiCad/share/kicad/library/Transistor
LibName96=C:/Program Files/KiCad/share/kicad/library/triac_thyristor
LibName97=C:/Program Files/KiCad/share/kicad/library/Valve
LibName98=C:/Program Files/KiCad/share/kicad/library/video
LibName99=C:/Program Files/KiCad/share/kicad/library/wiznet
LibName100=C:/Program Files/KiCad/share/kicad/library/Worldsemi
LibName101=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName102=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName103=C:/Program Files/KiCad/share/kicad/library/zetex
LibName104=C:/Program Files/KiCad/share/kicad/library/Zilog
LibName105=C:/Program Files/KiCad/share/kicad/library/graphic_symbols
LibName106=C:/Program Files/KiCad/share/kicad/library/nelieru_customs
LibName107=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName108=C:/Program Files/KiCad/share/kicad/library/74xx
LibName109=C:/Program Files/KiCad/share/kicad/library/actel
LibName110=C:/Program Files/KiCad/share/kicad/library/allegro
LibName111=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName112=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName113=C:/Program Files/KiCad/share/kicad/library/conn
LibName114=C:/Program Files/KiCad/share/kicad/library/leds
LibName115=C:/Program Files/KiCad/share/kicad/library/logo
LibName116=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName117=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName118=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName119=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName120=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName121=C:/Program Files/KiCad/share/kicad/library/microchip_pic24mcu
LibName122=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName123=C:/Program Files/KiCad/share/kicad/library/motors
LibName124=C:/Program Files/KiCad/share/kicad/library/msp430
LibName125=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName126=C:/Program Files/KiCad/share/kicad/library/relays
LibName127=C:/Program Files/KiCad/share/kicad/library/stm8
LibName128=C:/Program Files/KiCad/share/kicad/library/stm32
LibName129=C:/Program Files/KiCad/share/kicad/library/switches
LibName130=C:/Program Files/KiCad/share/kicad/library/transf
LibName131=C:/Program Files/KiCad/share/kicad/library/transistors
LibName132=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName133=C:/Program Files/KiCad/share/kicad/library/valves
